### ISSUE TITLE
Doesn't show up

### ISSUE THREAD

**Issue by OctoLiam** [tedhinklater/Jellyfin-Featured-Content-Bar#34]
I have tripled checked that I've followed all the steps correctly, even redoing the whole thing.

I have cleared cookies and cache a dozen or so time, even on different browsers.

Nothing will show, it creates the empty slot for it but nothing does show.

I added in the caddy line as required as well for reverse proxy, however locally accessing Jellyfin doesn't show it.
![image](https://github.com/user-attachments/assets/91efc615-241e-4d37-8748-dbcea6f6c309)

**Comment by tedhinklater** [comment]
It looks like the home-html edit is right (makes the space), but spotlight isn't loading. Just to check, you definitely downloaded spotlight.html with this button yep? (It would look like that if people saved the blob page rather than the file itself)

![389351733-30cf946b-7532-46c4-9f43-ad80ed22ea3f](https://github.com/user-attachments/assets/e00ff19f-3b01-4770-bdaf-8dab63af0f32)

**Comment by OctoLiam** [comment]
Ah I misread it every time and just noticing it says Line 2 also. Seems to work now, thank you!

(Sorry for my horrible reading)

**Comment by tedhinklater** [comment]
I've updated the guide to be a little clearer, hopefully save some future headaches!
