### ISSUE TITLE
Feature Request: option to display video aways muted

### ISSUE THREAD

**Issue by duduws** [tedhinklater/Jellyfin-Featured-Content-Bar#9]
The youtube video comes with enabled audio, is there an option to disable/mute the video in the feature request? so people still see the trailer but comes muted and then people choose to unmute or mute again, if there is any way to do that please i will really appreciate if anyone can help me do that.

**Comment by lattaai6** [comment]
Hello, I tried to fix the issue.

This is what I did:

Modified the code to mute YouTube videos by default and added an unmute button for users to control audio. The unmute button toggles between mute and unmute states, changing its icon and functionality accordingly.

You can review changes in this commit: https://github.com/lattaai6/tedhinklater-Jellyfin-Featured-Content-Bar-9/commit/45933b296f6b6955fb64327296cbc8afae58d069.


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This issue was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
